### PR TITLE
Fix footer mobile view

### PR DESCRIPTION
**Pull request by romanornr**
This fixes the footer rendering on top when you try to type on mobile.

Small change: The footer won't be 'sticky' footer.
I may look at it later

but if you add more content to the page, the footer will go down to the bottom of the page anyways.

### CODE REVIEW

**Comment by gmaxwell** [comment]
@romanornr The image is about 2500px across and so it loads somewhat slowly, could you put up a resized image?

**Comment by romanornr** [comment]
Sure, I just woke up. I will do that in a few minutes.

**Comment by romanornr** [comment]
Can you git cherry-pick this commit ? https://github.com/romanornr/bech32/commit/d886159424c19ececf3c480c7b6a5c1328d6ccd6

Can't make a pull request, Sipa changed his commit history according to github.

**Comment by sipa** [comment]
@romanornr Merged!

**Pull request merged**
