### PR TITLE
Validating 'zs' addresses with JavaScript

### PR DESCRIPTION
**Pull request by bomb-on**

### CODE REVIEW

**Comment by sipa** [comment]
What is a 'zs' address?

**Comment by bomb-on** [comment]
It's a Sapling z-address, used in Zcash and related coins.

https://z.cash/blog/whats-new-in-sapling/

**Comment by sipa** [comment]
segwit_addr.js is an implementation of BIP173 for Bitcoin. For other uses of Bech32 you should have a separate implementation, possibly reusing the Bech32 code.

**Comment by bomb-on** [comment]
Understood! Feel free to ignore/delete/reject this PR then :)

**Pull request closed without merging**
