### PR TITLE
Fix tests for non-v0 witnesses

### PR DESCRIPTION
**Pull request by sipa**
See corresponding BIP update: https://github.com/bitcoin/bips/pull/565

Thanks @afk11 for pointing this out.

### CODE REVIEW

**Comment by sipa** [comment]
@benma @clarkmoody @azuchi @tnakagawa You may want to know about this.

**Comment by tnakagawa** [comment]
ACK 0692344e85df3990eca4eaa1c81ec74063c461e8

**Comment by azuchi** [comment]
ACK

**Comment by clarkmoody** [comment]
ACK

**Comment by SamouraiDev** [comment]
ACK

**Pull request merged**
